version: '3.5'

volumes:
  mongodata:

services:
  mongo:
    container_name: suggestion-app-mongo
    image: mongo:5
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
